[package]
name = "day-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
nom.workspace = true
tracing.workspace = true
miette.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
plotters.workspace = true
divan.workspace = true
rstest.workspace = true
test-log.workspace = true
pretty_assertions.workspace = true

[[bench]]
name = "day-2-bench"
path = "benches/benchmarks.rs"
harness = false

[[bench]]
name = "day-2-bench-criterion"
path = "benches/benchmarks-criterion.rs"
harness = false
